on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow writing to repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make changes
        run: echo "New commit" >> test.txt

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update from GitHub Action"

      - name: Push changes to master
        run: git push origin master
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
