on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow writing to repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full git history to ensure all branches are accessible
          fetch-depth: 0
          token:: ${{ secrets.PAT_TOKEN }}

      - name: Make changes
        run: echo "New commit" >> test.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update from GitHub Action"

      - name: Push changes to master
        run: git push origin master
        #env:
        #  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
